export enum PaymentStatus {
  INITIATED = 'INITIATED',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  REFUSED = 'REFUSED',
  PENDING = 'PENDING',
  ERROR = 'ERROR',
}
